export const example = {
  status: "Ok!",
  message: "Successfully fetched all ClientesPorDesbloquear data!",
  data: {
    AUTOLLANTA: [
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
        ],
        sociosVinculados: [
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 26982,
            dcu_codigosocio: "C0913981494001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
        ],
        ClientePorDesbloquear: {
          empresa: "AUTOLLANTA",
          codigo_socio: "C0913981494001",
          codigo_cuenta_semanal: 13947,
          nombre_semanal: "PEREZ ESCALANTE LIRIO ECUADOR",
          dias_atraso_sabado: 92,
          valor_vencido_sabado: 339.25,
          codigo_cuenta_diario: 13947,
          nombre_diario: "PEREZ ESCALANTE LIRIO ECUADOR",
          dias_atraso_diario: 35,
          valor_vencido_diario: 238.79,
          tipo_desbloqueo: "DESBLOQUEO EN OTRAS EMPRESAS",
          promedio_dias_atraso_cheques: 13,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 5364,
            dcu_codigosocio: "C0102940525001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "AUTOLLANTA",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "AUTOLLANTA",
          codigo_socio: "C0102940525001",
          codigo_cuenta_semanal: 5364,
          nombre_semanal: "PATIÑO MUÑOZ ANIVAL MARCELO",
          dias_atraso_sabado: 2,
          valor_vencido_sabado: 537.58,
          codigo_cuenta_diario: null,
          nombre_diario: null,
          dias_atraso_diario: null,
          valor_vencido_diario: null,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: null,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 11029,
            dcu_codigosocio: "C0190001628001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "AUTOLLANTA",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "AUTOLLANTA",
          codigo_socio: "C0190001628001",
          codigo_cuenta_semanal: 11029,
          nombre_semanal: "AUSTRAL CIA LTDA",
          dias_atraso_sabado: 62,
          valor_vencido_sabado: 6.57,
          codigo_cuenta_diario: null,
          nombre_diario: null,
          dias_atraso_diario: null,
          valor_vencido_diario: null,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: null,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 28614,
            dcu_codigosocio: "C0102858511001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "AUTOLLANTA",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "AUTOLLANTA",
          codigo_socio: "C0102858511001",
          codigo_cuenta_semanal: 28614,
          nombre_semanal: "TORAL AGUILERA HUGO",
          dias_atraso_sabado: 4,
          valor_vencido_sabado: 142.03,
          codigo_cuenta_diario: null,
          nombre_diario: null,
          dias_atraso_diario: null,
          valor_vencido_diario: null,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: null,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 28789,
            dcu_codigosocio: "C1726285099001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "AUTOLLANTA",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "AUTOLLANTA",
          codigo_socio: "C1726285099001",
          codigo_cuenta_semanal: 28789,
          nombre_semanal: "MANOBANDA GALORA ALEXIS OLIVO",
          dias_atraso_sabado: 24,
          valor_vencido_sabado: 58.33,
          codigo_cuenta_diario: 28789,
          nombre_diario: "MANOBANDA GALORA ALEXIS OLIVO",
          dias_atraso_diario: 0,
          valor_vencido_diario: 0,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: null,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 12467,
            dcu_codigosocio: "C0301490686001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "AUTOLLANTA",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "AUTOLLANTA",
          codigo_socio: "C0301490686001",
          codigo_cuenta_semanal: 12467,
          nombre_semanal: "PEÑAFIEL GONZALEZ NORMA ESTRELLA",
          dias_atraso_sabado: 29,
          valor_vencido_sabado: 387.42,
          codigo_cuenta_diario: null,
          nombre_diario: null,
          dias_atraso_diario: null,
          valor_vencido_diario: null,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: null,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 6878,
            dcu_codigosocio: "C0103791471001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "AUTOLLANTA",
          },
          {
            dcu_codigo: 19290,
            dcu_codigosocio: "C0103791471001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "MAXXIMUNDO",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "AUTOLLANTA",
          codigo_socio: "C0103791471001",
          codigo_cuenta_semanal: 6878,
          nombre_semanal: "BARROS PEÑALOZA OSWALDO ENRIQUE",
          dias_atraso_sabado: 22,
          valor_vencido_sabado: 622.78,
          codigo_cuenta_diario: 6878,
          nombre_diario: "BARROS PEÑALOZA OSWALDO ENRIQUE",
          dias_atraso_diario: 7,
          valor_vencido_diario: 125.14,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: null,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 41888,
            dcu_codigosocio: "C1307376580001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "AUTOLLANTA",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "AUTOLLANTA",
          codigo_socio: "C1307376580001",
          codigo_cuenta_semanal: 41888,
          nombre_semanal: "LOOR MURILLO ANGEL LEONIDAS",
          dias_atraso_sabado: -4,
          valor_vencido_sabado: 0,
          codigo_cuenta_diario: 41888,
          nombre_diario: "LOOR MURILLO ANGEL LEONIDAS",
          dias_atraso_diario: -8,
          valor_vencido_diario: 0,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: 20,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 13075,
            dcu_codigosocio: "C0401345715001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "AUTOLLANTA",
          },
          {
            dcu_codigo: 20590,
            dcu_codigosocio: "C0401345715001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "MAXXIMUNDO",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "AUTOLLANTA",
          codigo_socio: "C0401345715001",
          codigo_cuenta_semanal: 13075,
          nombre_semanal: "CHARFUELAN MARTINEZ RICARDO MARCELO",
          dias_atraso_sabado: 1,
          valor_vencido_sabado: 631.06,
          codigo_cuenta_diario: null,
          nombre_diario: null,
          dias_atraso_diario: null,
          valor_vencido_diario: null,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: null,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 78298,
            dcu_codigosocio: "C0904798535001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "AUTOLLANTA",
          },
          {
            dcu_codigo: 36507,
            dcu_codigosocio: "C0904798535001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "AUTOLLANTA",
          codigo_socio: "C0904798535001",
          codigo_cuenta_semanal: 78298,
          nombre_semanal: "SAAD ROHA CESAR GUMARO",
          dias_atraso_sabado: 21,
          valor_vencido_sabado: 89.44,
          codigo_cuenta_diario: 78298,
          nombre_diario: "SAAD ROHA CESAR GUMARO",
          dias_atraso_diario: -22,
          valor_vencido_diario: 0,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: 29,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 28306,
            dcu_codigosocio: "C1105624033001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "AUTOLLANTA",
          },
          {
            dcu_codigo: 37116,
            dcu_codigosocio: "C1105624033001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "AUTOLLANTA",
          codigo_socio: "C1105624033001",
          codigo_cuenta_semanal: 28306,
          nombre_semanal: "APONTE SOCOLA ENMA MARICELA",
          dias_atraso_sabado: 20,
          valor_vencido_sabado: 666.34,
          codigo_cuenta_diario: null,
          nombre_diario: null,
          dias_atraso_diario: null,
          valor_vencido_diario: null,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: 9,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 14746,
            dcu_codigosocio: "C1205688870",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "AUTOLLANTA",
          },
          {
            dcu_codigo: 28721,
            dcu_codigosocio: "C1205688870",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "MAXXIMUNDO",
          },
          {
            dcu_codigo: 55066,
            dcu_codigosocio: "C1205688870",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "AUTOLLANTA",
          codigo_socio: "C1205688870",
          codigo_cuenta_semanal: 14746,
          nombre_semanal: "ACUÑA CARPIO RONALD FRANCISCO",
          dias_atraso_sabado: 100,
          valor_vencido_sabado: 39.6,
          codigo_cuenta_diario: null,
          nombre_diario: null,
          dias_atraso_diario: null,
          valor_vencido_diario: null,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: null,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 11197,
            dcu_codigosocio: "C0190314502001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "AUTOLLANTA",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "AUTOLLANTA",
          codigo_socio: "C0190314502001",
          codigo_cuenta_semanal: 11197,
          nombre_semanal:
            "TELECOMAUSTRO, INGENIERIA EN TELECOMUNICACIONES DEL AUSTRO CIA. LTDA.",
          dias_atraso_sabado: 42,
          valor_vencido_sabado: 832.46,
          codigo_cuenta_diario: null,
          nombre_diario: null,
          dias_atraso_diario: null,
          valor_vencido_diario: null,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: null,
          socios_vinculados: null,
        },
      },
    ],
    IKONIX: [
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 37393,
            dcu_codigosocio: "C1719445080001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "IKONIX",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "IKONIX",
          codigo_socio: "C1719445080001",
          codigo_cuenta_semanal: 37393,
          nombre_semanal: "CHANGO MORETA ALEXANDRA KARINA",
          dias_atraso_sabado: 29,
          valor_vencido_sabado: 73.31,
          codigo_cuenta_diario: 37393,
          nombre_diario: "CHANGO MORETA ALEXANDRA KARINA",
          dias_atraso_diario: -22,
          valor_vencido_diario: 0,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: null,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 29188,
            dcu_codigosocio: "C0103005625001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "IKONIX",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "IKONIX",
          codigo_socio: "C0103005625001",
          codigo_cuenta_semanal: 29188,
          nombre_semanal: "ORDOÑEZ ALVARADO GLADYS AGAR",
          dias_atraso_sabado: 23,
          valor_vencido_sabado: 59.06,
          codigo_cuenta_diario: 29188,
          nombre_diario: "ORDOÑEZ ALVARADO GLADYS AGAR",
          dias_atraso_diario: -26,
          valor_vencido_diario: 0,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: null,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 1382089,
            dcu_codigosocio: "C0105598080001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "IKONIX",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "IKONIX",
          codigo_socio: "C0105598080001",
          codigo_cuenta_semanal: 1382089,
          nombre_semanal: "YUQUILIMA UZHCA KARINA ALEXANDRA",
          dias_atraso_sabado: 42,
          valor_vencido_sabado: 152.62,
          codigo_cuenta_diario: 1382089,
          nombre_diario: "YUQUILIMA UZHCA KARINA ALEXANDRA",
          dias_atraso_diario: -6,
          valor_vencido_diario: 0,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: null,
          socios_vinculados: null,
        },
      },
    ],
    STOX: [
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 57886,
            dcu_codigosocio: "C1191797304001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
        ],
        sociosVinculados: [
          {
            dcu_codigo: 14554,
            dcu_codigosocio: "C1104020803001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "AUTOLLANTA",
          },
          {
            dcu_codigo: 21479,
            dcu_codigosocio: "C1104020803001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "MAXXIMUNDO",
          },
          {
            dcu_codigo: 27221,
            dcu_codigosocio: "C1104020803001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
        ],
        ClientePorDesbloquear: {
          empresa: "STOX",
          codigo_socio: "C1191797304001",
          codigo_cuenta_semanal: 57886,
          nombre_semanal: "RG TECNICENTRO TIRESHOP S.A.S.",
          dias_atraso_sabado: 1,
          valor_vencido_sabado: 57.54,
          codigo_cuenta_diario: 57886,
          nombre_diario: "RG TECNICENTRO TIRESHOP S.A.S.",
          dias_atraso_diario: -22,
          valor_vencido_diario: 0,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: 5,
          socios_vinculados: "C1104020803001",
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 27733,
            dcu_codigosocio: "C1723651640001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 15753,
            dcu_codigosocio: "C1723651640001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "AUTOLLANTA",
          },
          {
            dcu_codigo: 22503,
            dcu_codigosocio: "C1723651640001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "MAXXIMUNDO",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "STOX",
          codigo_socio: "C1723651640001",
          codigo_cuenta_semanal: 27733,
          nombre_semanal: "ALBA ULCUANGO CARLOS EDUARDO",
          dias_atraso_sabado: 370,
          valor_vencido_sabado: 178.89,
          codigo_cuenta_diario: null,
          nombre_diario: null,
          dias_atraso_diario: null,
          valor_vencido_diario: null,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: 383,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 27574,
            dcu_codigosocio: "C1711932549001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 15491,
            dcu_codigosocio: "C1711932549001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "AUTOLLANTA",
          },
        ],
        sociosVinculados: [
          {
            dcu_codigo: 22116,
            dcu_codigosocio: "C1710451442001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "MAXXIMUNDO",
          },
          {
            dcu_codigo: 27549,
            dcu_codigosocio: "C1710451442001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
        ],
        ClientePorDesbloquear: {
          empresa: "STOX",
          codigo_socio: "C1711932549001",
          codigo_cuenta_semanal: 27574,
          nombre_semanal: "TERAN CALDERON ROSITA ADELA",
          dias_atraso_sabado: 1,
          valor_vencido_sabado: 237.34,
          codigo_cuenta_diario: 27574,
          nombre_diario: "TERAN CALDERON ROSITA ADELA",
          dias_atraso_diario: -83,
          valor_vencido_diario: 0,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: 12,
          socios_vinculados: "C1710451442001",
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 27164,
            dcu_codigosocio: "C1091772171001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 21378,
            dcu_codigosocio: "C1091772171001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "MAXXIMUNDO",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "STOX",
          codigo_socio: "C1091772171001",
          codigo_cuenta_semanal: 27164,
          nombre_semanal:
            "COMERCIALIZADORA MULTIMARCAS JC COMERLLANT CIA.LTDA.",
          dias_atraso_sabado: 148,
          valor_vencido_sabado: 2500,
          codigo_cuenta_diario: 27164,
          nombre_diario: "COMERCIALIZADORA MULTIMARCAS JC COMERLLANT CIA.LTDA.",
          dias_atraso_diario: -26,
          valor_vencido_diario: 0,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: 141,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 26525,
            dcu_codigosocio: "C0105525695001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 19836,
            dcu_codigosocio: "C0105525695001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "MAXXIMUNDO",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "STOX",
          codigo_socio: "C0105525695001",
          codigo_cuenta_semanal: 26525,
          nombre_semanal: "PAGUAY ABAD PABLO MARTIN",
          dias_atraso_sabado: 101,
          valor_vencido_sabado: 534.58,
          codigo_cuenta_diario: 26525,
          nombre_diario: "PAGUAY ABAD PABLO MARTIN",
          dias_atraso_diario: 15,
          valor_vencido_diario: 0.01,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: null,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 27450,
            dcu_codigosocio: "C1700967316001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "STOX",
          codigo_socio: "C1700967316001",
          codigo_cuenta_semanal: 27450,
          nombre_semanal: "CASTILLO MORENO LUIS ALONSO",
          dias_atraso_sabado: 29,
          valor_vencido_sabado: 306,
          codigo_cuenta_diario: 27450,
          nombre_diario: "CASTILLO MORENO LUIS ALONSO",
          dias_atraso_diario: 5,
          valor_vencido_diario: 43.8,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: 39,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 27606,
            dcu_codigosocio: "C1714219407001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 15556,
            dcu_codigosocio: "C1714219407001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "AUTOLLANTA",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "STOX",
          codigo_socio: "C1714219407001",
          codigo_cuenta_semanal: 27606,
          nombre_semanal: "BLACIO TITUANA ERASMO HERNAN",
          dias_atraso_sabado: 23,
          valor_vencido_sabado: 860.37,
          codigo_cuenta_diario: 27606,
          nombre_diario: "BLACIO TITUANA ERASMO HERNAN",
          dias_atraso_diario: -1,
          valor_vencido_diario: 0,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: null,
          socios_vinculados: "C0704076413001",
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 36658,
            dcu_codigosocio: "C1103539878001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 21450,
            dcu_codigosocio: "C1103539878001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "MAXXIMUNDO",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "STOX",
          codigo_socio: "C1103539878001",
          codigo_cuenta_semanal: 36658,
          nombre_semanal: "TAMAY CUENCA DARWIN ALEXANDER",
          dias_atraso_sabado: 46,
          valor_vencido_sabado: 372.61,
          codigo_cuenta_diario: 36658,
          nombre_diario: "TAMAY CUENCA DARWIN ALEXANDER",
          dias_atraso_diario: 20,
          valor_vencido_diario: 442.15,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: 24,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 36691,
            dcu_codigosocio: "C1600563991001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "STOX",
          codigo_socio: "C1600563991001",
          codigo_cuenta_semanal: 36691,
          nombre_semanal: "SISA ANDAGANA JESSICA LISBETH",
          dias_atraso_sabado: 21,
          valor_vencido_sabado: 91.19,
          codigo_cuenta_diario: null,
          nombre_diario: null,
          dias_atraso_diario: null,
          valor_vencido_diario: null,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: 21,
          socios_vinculados: "C1600404907001",
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 27183,
            dcu_codigosocio: "C1102437413001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "STOX",
          codigo_socio: "C1102437413001",
          codigo_cuenta_semanal: 27183,
          nombre_semanal: "ROMAN VALDIVIESO MAURICIO FERNANDO",
          dias_atraso_sabado: 17,
          valor_vencido_sabado: 32.81,
          codigo_cuenta_diario: 27183,
          nombre_diario: "ROMAN VALDIVIESO MAURICIO FERNANDO",
          dias_atraso_diario: -5,
          valor_vencido_diario: 0,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: 23,
          socios_vinculados: null,
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 27228,
            dcu_codigosocio: "C1104305717001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 21493,
            dcu_codigosocio: "C1104305717001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "MAXXIMUNDO",
          },
        ],
        sociosVinculados: [
          {
            dcu_codigo: 36446,
            dcu_codigosocio: "C1104172729001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
        ],
        ClientePorDesbloquear: {
          empresa: "STOX",
          codigo_socio: "C1104305717001",
          codigo_cuenta_semanal: 27228,
          nombre_semanal: "TOALONGO GONZALEZ NOEMI EUGENIA",
          dias_atraso_sabado: 18,
          valor_vencido_sabado: 449.91,
          codigo_cuenta_diario: 27228,
          nombre_diario: "TOALONGO GONZALEZ NOEMI EUGENIA",
          dias_atraso_diario: -6,
          valor_vencido_diario: 0,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: null,
          socios_vinculados: "C1104172729001",
        },
      },
      {
        desbloqueo: true,
        cuentasDesbloqueo: [
          {
            dcu_codigo: 36166,
            dcu_codigosocio: "C0103248696001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "STOX",
          },
          {
            dcu_codigo: 19093,
            dcu_codigosocio: "C0103248696001",
            dcu_bloqueocartera: "SI",
            dcu_empresa: "MAXXIMUNDO",
          },
        ],
        sociosVinculados: [],
        ClientePorDesbloquear: {
          empresa: "STOX",
          codigo_socio: "C0103248696001",
          codigo_cuenta_semanal: 36166,
          nombre_semanal: "ROMERO DORYS DEL ROCIO",
          dias_atraso_sabado: 35,
          valor_vencido_sabado: 267.5,
          codigo_cuenta_diario: null,
          nombre_diario: null,
          dias_atraso_diario: null,
          valor_vencido_diario: null,
          tipo_desbloqueo: "DESBLOQUEO TOTAL",
          promedio_dias_atraso_cheques: 44,
          socios_vinculados: null,
        },
      },
    ],
  },
};
