export const MODULES_FLAT = {
  /* Los siguientes no disponene de permiso, son publicos */
  LOGIN: "LOGIN",
  PORTAL: "HOME",
  RECOVERY: "RECOVERY",

  /* ---------------------------------------------------- */
  CARTERA: "CARTERA",
  REGISTROS_BANCARIOS: "REGISTROSBANCARIOS",
  H_REGISTROS_BANCARIOS: "REGISTROS HISTORICOS",
  SUBIR_ARCHIVO: "SUBIR ARCHIVO",
  GESTION_CHEQUES: "GESTION CHEQUES",
  DESBLOQUEO_CLIENTES: "DESBLOQUEO CLIENTES",

  COMPRAS: "COMPRAS",
  GRAFICAS: "GRAFICAS",
  IMPORTACIONES: "IMPORTACIONES",
  GENERAL: "GENERAL",
  BODEGA: "BODEGA",
  GERENCIA: "COMPRAS-GERENCIA",
  CREDITOS: "CREDITOS",
  ANTICIPOS: "ANTICIPOS",

  MRP: "MRP",
  ASIGNACIONES: "ASIGNACIONES",
  PROMOCIONES: "PROMOCIONES",
  CREAR: "CREAR PROMOCION",
  CONSULTAR: "CONSULTAR PROMOCION",
  CARGAR_ARCHIVO: "CARGAR ARCHIVO",
  PARAMETRIZACIONES: "PARAMETRIZACION",
  SIMULACION: "SIMULACION",
  SIMULACION_COMERCIAL: "PEDIDOS COMERCIAL",

  CONTABILIDAD: "CONTABILIDAD",
  CONVERSION: "CONVERSION",
  REPORTE_FLUJOCAJA: "REPORTE_FLUJOCAJA",
  COMISIONES: "COMISIONES",
  MAYORISTAS: "MAYORISTAS",
  TECNICENTRO: "TECNICENTRO",
  TECNICENTRO_CATEGORIAS: "TECNICENTRO_PRODUCTOS",

  MARKETING: "MARKETING",
  INVENTARIO: "INVENTARIO",
  FACTURACIONMP: "FACTURACIONMP",
  COMERCIALREP: "COMERCIALREP",

  GESTION_CLIENTES: "GESTIONCLIENTES",
  REPORTES: "REPORTES",
  REPORTES_SEGM: "REPORTES_SEGM",
  NEUMATICOS: "NEUMATICOS",
  NEUMATICOS_MOTO: "NEUMATICOS MOTO",
  LUBRICANTES: "LUBRICANTES",

  RRHH: "RRHH",
  DOCUMENTACION: "DOCUMENTACION",

  GOBIERNO_DATOS: "GOBIERNODATOS",
  MAESTROS: "MAESTROS",

  CYMC: "CYMC",

  ADMINISTRACION: "ADMINISTRACION",
};

export const MODULES_TREE = {
  /* Los siguientes no disponene de permiso, son publicos */
  LOGIN: "LOGIN",
  PORTAL: "HOME",
  RECOVERY: "RECOVERY",

  /* ---------------------------------------------------- */
  CARTERA: {
    REGISTROS_BANCARIOS: "REGISTROS BANCARIOS",
    H_REGISTROS_BANCARIOS: "REGISTROS HISTORICOS",
    SUBIR_ARCHIVO: "SUBIR ARCHIVO",
    GESTION_CHEQUES: "GESTION CHEQUES",
    DESBLOQUEO_CLIENTES: "DESBLOQUEO CLIENTES",
  },
  COMPRAS: {
    GRAFICAS: "GRAFICAS",
    IMPORTACIONES: {
      GENERAL: "IMPORTACIONES",
      BODEGA: "BODEGA",
      GERENCIA: "COMPRAS-GERENCIA",
    },
    CREDITOS: "CREDITOS",
    ANTICIPOS: "ANTICIPOS",
  },
  MRP: {
    ASIGNACIONES: "ASIGNACIONES",
    PROMOCIONES: {
      CREAR: "CREAR PROMOCION",
      CONSULTAR: "CONSULTAR PROMOCION",
      CARGAR_ARCHIVO: "CARGAR ARCHIVO",
    },
    PARAMETRIZACIONES: "PARAMETRIZACION",
    SIMULACION: "SIMULACION",
    SIMULACION_COMERCIAL: "PEDIDOS COMERCIAL",
  },
  CONTABILIDAD: {
    CONVERSION: "CONVERSION",
    REPORTE_FLUJOCAJA: "REPORTE_FLUJOCAJA",
    COMISIONES: {
      MAYORISTAS: "MAYORISTAS",
      TECNICENTRO: "TECNICENTRO",
      TECNICENTRO_CATEGORIAS: "TECNICENTRO_PRODUCTOS",
      LUBRICANTES: "LUBRICANTES",
    },
  },
  MARKETING: {
    INVENTARIO: "INVENTARIO",
    FACTURACIONMP: "FACTURACIONMP",
    COMERCIALREP: "COMERCIALREP",
  },
  RRHH: {
    DOCUMENTACION: "DOCUMENTACION",
  },
  GESTION_CLIENTES: {
    REPORTES: "REPORTES",
    REPORTES_SEGM: {
      NEUMATICOS: "NEUMATICOS",
      NEUMATICOS_MOTO: "NEUMATICOS MOTO",
      LUBRICANTES: "LUBRICANTES",
    },
  },
  GOBIERNO_DATOS: {
    MAESTROS: "MAESTROS",
  },
  TECNICENTRO: {
    REPORTES: "REPORTES",
  },
  CYMC: {
    REPORTES: "REPORTES",
  },
  ADMINISTRACION: "ADMINISTRACION",
};
